name: test

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: checkout the repository
          uses: actions/checkout@v4
        - name: checkout the repository
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 18
        - run: npm install
        - uses: actions/cache@v3
          id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          with:
            path: ${{ steps.npm-cache-dir.outputs.dir }}
            key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        